dismiss flow fix for work with external werf values

diff --git a/.github/workflows/dismiss.yaml b/.github/workflows/dismiss.yaml
--- a/.github/workflows/dismiss.yaml
+++ b/.github/workflows/dismiss.yaml
@@ -15,6 +15,14 @@ on:
         description: "ID for namespace and helm release name"
         required: true
         type: string
+      values:
+        description: "Helm values from github as yaml"
+        required: false
+        type: string
+      branch_id:
+        description: "Branch name for checkout"
+        required: false
+        type: string        
       remove_ns:
         description: "Remove or not NS by werf"
         required: false
@@ -30,11 +38,14 @@ on:
         required: true
       KUBECONFIG_DATA: 
         required: true
+      SECRETS_CONTEXT:
+        required: false
  
 env:
   WERF_REPO: ${{ format ('{0}/images/{1}', secrets.HARBOR_HOST, inputs.project_id) }}
   WERF_REPO_CONTAINER_REGISTRY: harbor
   WERF_DIR: ${{ format ('{0}/{1}/werf', inputs.project_id, inputs.project_path) }}
+  GITHUB_SECRETS_LIST: ${{ format ('{0}/{1}/werf/github.secrets', inputs.project_id, inputs.project_path) }}
   
 jobs:
   common_dismiss:
@@ -42,10 +53,68 @@ jobs:
     runs-on: ubuntu-latest
     steps:
 
-    - name: "Checkout code"
+    - name: "Checkout code with ref ${{ inputs.branch_id }}"
       uses: actions/checkout@v2
+      if: ${{ inputs.branch_id != '' }}
       with:
         fetch-depth: 0
+        ref: ${{ inputs.branch_id }}
+
+    - name: "Checkout code"
+      uses: actions/checkout@v2
+      if: ${{ inputs.branch_id == '' }}
+      with:
+        fetch-depth: 0
+
+    - name: "Github values"
+      run: |
+        if [[ -n "${values_github}" ]]; then
+          echo -e "\n#### Install yq"
+          curl -sLo yq https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_amd64 && chmod +x yq
+
+          echo -e "\n#### Export github variables"
+          json=$(echo "$values_github" | yq -o json)
+
+          for key in $(echo "$json" | jq -r 'keys[]'); do
+            echo "Processing '$key'"
+            value=$(echo "$json" | jq --arg key $key '.[$key]')
+
+            echo "Export variable '$key'"
+            echo "$key<<EOF" >> $GITHUB_ENV
+            echo "$value" >> $GITHUB_ENV
+            echo "EOF" >> $GITHUB_ENV
+          done
+        fi
+
+        if [[ -f "$GITHUB_SECRETS_LIST" ]]; then 
+          echo -e "\n#### Export secret values"
+
+          for secret in $(cat "$GITHUB_SECRETS_LIST"); do
+            echo "Processing '$secret'"
+            var=''
+            for var in "$secret" "${env_id^^}_${secret}"; do
+              value=$(echo "${SECRETS_CONTEXT}" | jq -r --arg var "$var" '.[$var]')
+              if [[ "$value" != "null" ]]; then break; fi
+            done
+
+            if [[ "$value" == "null" ]]; then
+              echo "Cannot find any secret '$secret' or '$var'"
+              exit 1
+            fi
+            
+            key=$(sed -r 's/(^|_)(\w)/\U\2/g' <<<"${secret,,}")
+
+            echo "Export secret '$var' as '$key'"
+            echo "$key<<EOF" >> $GITHUB_ENV
+            echo "$value" >> $GITHUB_ENV
+            echo "EOF" >> $GITHUB_ENV
+          done
+        fi
+      shell: bash
+      env:
+        SECRETS_CONTEXT: ${{ secrets.SECRETS_CONTEXT }}
+        env_id: ${{ inputs.env_id }}
+        values_github: "${{ inputs.values }}"
 
     - name: "Login to Harbor"
       uses: docker/login-action@v1
